    - name: Cria usuário para o Node Exporter
      ansible.builtin.user:
        name: node_exporter
        shell: /usr/sbin/nologin
        system: yes
        create_home: no

    - name: Baixa o Node Exporter
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Descompacta o Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move o binário do Node Exporter
      ansible.builtin.copy:
        src: /tmp/node_exporter-1.8.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Cria o serviço systemd para o Node Exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          ExecStart=/usr/local/bin/node_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Recarrega o systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Inicia e habilita o Node Exporter
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: yes