    - name: Adiciona chave GPG do repositório Grafana
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Adiciona repositório Grafana
      ansible.builtin.apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Atualiza o cache APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Instala o pacote Grafana
      ansible.builtin.apt:
        name: grafana
        state: present

    - name: Habilita e inicia o serviço Grafana
      ansible.builtin.service:
        name: grafana-server
        enabled: yes
        state: started

        