- name: Instala o Node Exporter
  import_tasks: install_node_exporter.yml

- name: Instala o Prometheus
  import_tasks: install_prometheus.yml

- name: Instala o Alertmanager
  import_tasks: install_alertmanager.yml

- name: Instala o Grafana
  import_tasks: install_grafana.yml

- name: Cria DataSource Prometheus no Grafana
  import_tasks: configure_grafana_datasource.yml

- name: Verifica status dos servi√ßos
  import_tasks: verify_services.yml